### ISSUE TITLE
iOS implemention with SecKey methods

### ISSUE THREAD

**Issue by amitaymolko** [amitaymolko/react-native-rsa-native#2]
Implement with built in iOS lib so we don't have to bundle openssl in.
https://developer.apple.com/library/content/documentation/Security/Conceptual/CertKeyTrustProgGuide/KeyGen.html#//apple_ref/doc/uid/TP40001358-CH212-SW1

**Comment by crafterm** [comment]
Looks like SecKeyGeneratePair/SecKeyEncrypt/SecKeyDecrypt would drop in well in the RSANative 
 API method signatures you currently have.

The setPublicKey methods could remain intact if you'd like to support being able to pass the literal public/private key content in as strings - but an alternative could be to:

* break this and have the string passed to setPublicKey be a reference to a key chain stored item name/tag, or
* add an additional method to do the above, and support both options

Not sure what you're use case is mate? What do you think? 

Our use case is the former since we're after a keychain stored key, and SecKeyGeneratePair can create it directly into the keychain or even better, directly into the secure enclave in case of the private key.

**Comment by amitaymolko** [comment]
I think we should support both string and keychain.
I will try to implement SecKey for iOS this weekend.
Do you want to add keychain support after that?

**Comment by crafterm** [comment]
@amitaymolko ok mate, I have some SecKey code coming together at the moment, will point you to a WIP PR shortly

**Comment by amitaymolko** [comment]
release in PR #5 Great job @crafterm!

**Comment by crafterm** [comment]
@amitaymolko thanks mate!
